# Generated by Django 5.2.17 on 2026-09-09 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
    ]
