# Generated by Django 5.2.17 on 2026-09-04 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(max_length=20)),
                ('sentiment_score', models.FloatField(default=0)),
                ('emotion', models.CharField(blank=True, max_length=80)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('summary', models.TextField(blank=True)),
                ('complaint', models.TextField(blank=True)),
                ('feature_request', models.TextField(blank=True)),
                ('priority', models.CharField(default='MEDIUM', max_length=20)),
                ('confidence', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feedback', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='feedback.feedback')),
            ],
        ),
    ]
