# Generated by Django 5.2.17 on 2026-09-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.PositiveBigIntegerField()),
                ('date', models.DateField()),
                ('total_feedback', models.PositiveIntegerField(default=0)),
                ('positive', models.PositiveIntegerField(default=0)),
                ('neutral', models.PositiveIntegerField(default=0)),
                ('negative', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
